---
name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DEFAULT_PHP: "8.3"
  DEFAULT_FOLDER: "./laravel"

jobs:
  pint:
    name: 🧹 Laravel Pint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: 🏗 Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: ${{env.DEFAULT_PHP}}

      - name: 🏗 Install Laravel Dependencies
        working-directory: ${{env.DEFAULT_FOLDER}}
        run: |
          composer install -n --prefer-dist

      - name: 🚀 Run Laravel Pint
        working-directory: ${{env.DEFAULT_FOLDER}}
        run: ./vendor/bin/pint --test
